### ISSUE TITLE
PodSecurityPolicy was deprecated in Kubernetes v1.21, and removed from Kubernetes in v1.25

### ISSUE THREAD

**Issue by steveardis** [hivemq/helm-charts#100]
When running `helm upgrade --install hivemq hivemq/hivemq-operator` on 1.25.4, the following error occures:

```
Release "hivemq" does not exist. Installing it now.
Error: unable to build kubernetes objects from release manifest: resource mapping not found for name: "hivemq-hivemq-operator" namespace: "default" from "": no matches for kind "PodSecurityPolicy" in version "policy/v1beta1"
ensure CRDs are installed first
```

See:
https://kubernetes.io/docs/concepts/security/pod-security-policy/

Specifically:

> PodSecurityPolicy was [deprecated](https://kubernetes.io/blog/2021/04/08/kubernetes-1-21-release-announcement/#podsecuritypolicy-deprecation) in Kubernetes v1.21, and removed from Kubernetes in v1.25.

**Comment by hurtadosanti** [comment]
Hi @steveardis thanks for reaching out. To use the helm-chart for versions >1.24 you have to disable the pod security policies like this:
```
global:
  rbac:
    pspEnabled: false
```
