### ISSUE TITLE
Decouple Operator and Cluster from each other in Helm Chart

### ISSUE THREAD

**Issue by hertfelder** [hivemq/helm-charts#19]
Hi Guys,

Wouldn't it be sensible to decouple the installation of the operator and of the cluster? Right now, both are in the same helm chart. I know, I can switch off the creation of a cluster (`deployCr: false`), but it seems like I cannot do it the other way round.

I imagine a typical use case would be like:
* Deploy the Operator once
* Deploy/Update clusters multiple times

I do not see how I can do this conveniently with the helm chart provided. I would expect one Helm chart for deploying and maintaining the operator (upgrade, ...). In addition, I would expect a second Helm chart for deploying a CR, i.e. a cluster. This helm chart would be installed several times with differing names (prod cluster, int cluster, ...) and I can manage the lifecycle of the clusters independently of each other and of the operator.

Also the documentation (https://www.hivemq.com/docs/operator/4.6/kubernetes-operator/configuration.html) is a bit fishy in my opinion. At first, it deals with the values for the Helm chart. But at some point it switches to resource files of `kind: HiveMQCluster`.

Does this make sense to you or is there a misunderstanding on my side?

Thanks,
Marius
(Enterprise Customer via Daimler AG - VehicleDiagnosticsSystem)

**Comment by marleau** [comment]
Regarding the documentation, I also think it needs work. It switches between Helm and Kubernetes config yaml files without explanation. I'm new to Kubernetes, so this is very confusing to me. For now, I have abandoned the helm chart and am managing my HiveMQ cluster with my own yaml files.
