### ISSUE TITLE
Docs: Description for noConnectIdleTimeout says seconds instead of miliseconds

### ISSUE THREAD

**Issue by hertfelder** [hivemq/helm-charts#23]
See:
https://www.hivemq.com/docs/operator/4.6/kubernetes-operator/configuration.html#basic

noConnectIdleTimeout | 10000 | The time in seconds that HiveMQ waits for the CONNECT message of a client before closing an open TCP socket
-- | -- | --

And:
https://www.hivemq.com/docs/hivemq/4.6/user-guide/restrictions.html#connection-timeouts

no-connect-idle-timeout | 10000 | The time in milliseconds that HiveMQ waits for a CONNECT message of a client before an open TCP socket is closed.
-- | -- | --

**Comment by hurtadosanti** [comment]
Thanks for your contribution, @hertfelder this was now fixed here: https://www.hivemq.com/docs/operator/latest/kubernetes-operator/configuration.html#basic
