### ISSUE TITLE
Facing issues with the secure websocket config !!

### ISSUE THREAD

**Issue by puneetmathur-87** [hivemq/helm-charts#24]
I am trying to enable the secure web socket on the hivemq and using below config file and mounting appropriate key store and truststores.
This is my values file:

hivemq:
  nodeCount: 3
  cpu: 200m
  memory: 3072M
  listenerConfiguration: |
    <websocket-listener>
          <port>8001</port>
          <bind-address>0.0.0.0</bind-address>
          <path>/mqtt</path>
          <name>my-websocket-listener</name>
          <subprotocols>
              <subprotocol>mqttv3.1</subprotocol>
              <subprotocol>mqtt</subprotocol>
          </subprotocols>
          <allow-extensions>false</allow-extensions>
          <tls>
            <protocols>
                </protocols>
               <keystore>
                   <path>/etc/hivemqstore/hivemq.jks</path>
                   <password>123456</password>
                   <private-key-password>123456</private-key-password>
               </keystore>
               <truststore>
                    <path>/etc/hivemqstore/hivemqtrust.jks</path>
                    <password>123456</password>
                </truststore>
               <client-authentication-mode>NONE</client-authentication-mode>
           </tls>
      </websocket-listener>
  ports:
    - name: "mqtt"
      port: 8001
      expose: true
      patch:
      - '[{"op":"add","path":"/spec/selector/hivemq.com~1node-offline","value":"false"},{"op":"add","path":"/metadata/annotations","value":{"service.spec.externalTrafficPolicy":"Local"}}]'
      # If you want Kubernetes to expose the MQTT port
      - '[{"op":"add","path":"/spec/type","value":"LoadBalancer"}]'
    - name: "cc"
      port: 8080
      expose: true
      patch:
        - '[{"op":"add","path":"/spec/type","value":"LoadBalancer"}]'
#      - '[{"op":"add","path":"/spec/sessionAffinity","value":"ClientIP"}]'
  configMaps:
    - name: "hivemqstore" 
      path: "/etc/hivemqstore"
  #secrets: [ {"name": "hivemqstore", "path": "/opt/hivemq/hivemq.jks"}, ]

**Comment by hurtadosanti** [comment]
Hi @puneetmathur-87 can you please format correctly the value file to be able to verify.
