### ISSUE TITLE
Default CPU is not 1 CPU

### ISSUE THREAD

**Issue by tim-reply** [hivemq/helm-charts#259]
Default config specifies 1024m CPU in resources here:
https://github.com/hivemq/helm-charts/blob/b4e11122775be3acf2eff601aa4c840ff8a0aee4/charts/hivemq-platform/values.yaml#L26

Suffix "m" means milli, i.e 0.001 of CPU - it is regular decimal power, not power-of-two, so if intention was to default to 1 CPU, that was not done correctly.

**Comment by afalhambra-hivemq** [comment]
Hello @tim-reply, thanks for your feedback.
However, 1 CPU = 1000 milicores, so in our case we are giving a little more than 1 CPU but not less.
