### ISSUE TITLE
hivemq-platform-operator: when service account is not created, Service is also not created

### ISSUE THREAD

**Issue by avthart** [hivemq/helm-charts#324]
See: https://github.com/hivemq/helm-charts/blob/master/charts/hivemq-platform-operator/templates/service.yml#L1

Probably due to copy-paste?

**Comment by afalhambra-hivemq** [comment]
Thanks a lot @avthart for reporting this. It is indeed a bug here.
Will raise a PR soon to fix this.

Keep you updated.

**Comment by afalhambra-hivemq** [comment]
Fixed by https://github.com/hivemq/helm-charts/pull/361
