### ISSUE TITLE
Configure securityContext by default for implementing Pod Security Standard

### ISSUE THREAD

**Issue by avthart** [hivemq/helm-charts#325]
In compliant Kubernetes clusters, workloads should run as secure as possible. 
Therefore, it would be great if hivemq and the operator can be compliant with the Pod Security Standard restricted profile (if possible).  

See https://kubernetes.io/docs/concepts/security/pod-security-standards/

**Comment by avthart** [comment]
Currently it is possible to set the podSecurityContext but it is not possible to set the containerSecurityContext (e.g. drop all capabilities, allowPrivilegeEscalation to false).

**Comment by afalhambra-hivemq** [comment]
Thanks @avthart - Indeed, that's a valid point to improve the Pod Security Standard of our platform.
That's something we are not directly supporting via our Helm charts. I will work on this to provide support for the Container Security Context as well.

In the meantime, if you need that, you can always override the whole StatefulSet as mentioned in our HiveMQ [documentation](https://docs.hivemq.com/hivemq-platform-operator/configuration.html#platform-configuration-options-helm). Bear in mind, that doing so, you need to align the different service configuration you also may have in your custom chart values with the ones you define in your override StatefulSet.

**Comment by avthart** [comment]
Thanks. Will look into this!

**Comment by afalhambra-hivemq** [comment]
Fixed by https://github.com/hivemq/helm-charts/pull/361
