### ISSUE TITLE
Failed to create resource: Internal error occurred: failed calling webhook "hivemq-cluster-policy.hivemq.com"

### ISSUE THREAD

**Issue by mokhos** [hivemq/helm-charts#53]
## Expected behavior
Helmchart to be installed correctly!
## Actual behavior
Giving this error without any special configuration or change in helmchart:
`
failed to create resource: Internal error occurred: failed calling webhook "hivemq-cluster-policy.hivemq.com": Post "https://hivemq-operator-0-1649064099-operator.hivemq.svc:443/api/v1/validate/hivemq-clusters?timeout=30s": service "hivemq-operator-0-1649064099-operator" not found
`
How it is looking for its service with a different name, while the service is created with another name?
### Steps
https://www.hivemq.com/docs/operator/4.7/kubernetes-operator/deploying.html#helm-chart

**Comment by stefanjay** [comment]
Bumping this one - when do we can expect a patched helm chart?

**Comment by hurtadosanti** [comment]
Hi @mokhos can you please clarify which steps you mean? What version of K8s are you using? Which processor architecture has your machine or which cloud provider are you using?
