### ISSUE TITLE
policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+ #1658

### ISSUE THREAD

**Issue by sarathi190590** [hivemq/helm-charts#80]
policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+ #1658
please help on this

**Comment by hurtadosanti** [comment]
Please disable the PodSecurityPolicy:
`global:
  rbac:
    pspEnabled: false`
