### ISSUE TITLE
Quickstart doesn't start cluster / Stuck on PENDING

### ISSUE THREAD

**Issue by leovanalphen** [hivemq/helm-charts#84]
Hi,

I'm trying to start a test hivemq cluster on k8s using the quickstart guide (https://www.hivemq.com/docs/operator/4.8/kubernetes-operator/deploying.html#deploy-operator).

I've added the hivemq helm repo and ran the command helm upgrade --install hivemq hivemq/hivemq-operator.

During this deployment I see one error, but I'm not sure it is related:
W0926 14:47:02.100015  121077 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
W0926 14:47:02.879929  121077 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
W0926 14:47:03.103902  121077 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
I0926 14:47:34.943124  121077 trace.go:205] Trace[183458752]: "Reflector ListAndWatch" name:k8s.io/client-go@v0.23.4/tools/cache/reflector.go:167 (26-Sep-2022 14:47:04.896) (total time: 30046ms):
Trace[183458752]: ---"Objects listed" error:<nil> 30046ms (14:47:34.943)
Trace[183458752]: [30.046624755s] [30.046624755s] END
W0926 14:47:35.028430  121077 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
W0926 14:47:35.304094  121077 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
W0926 14:48:05.788086  121077 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
W0926 14:48:05.953539  121077 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
W0926 14:48:10.756457  121077 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
NAME: hivemq
LAST DEPLOYED: Mon Sep 26 14:47:01 2022
NAMESPACE: default
STATUS: deployed
REVISION: 1

The operator is started, I see no errors on the operator. But when I do cm kubectl get hivemq-clusters, the status stays on PENDING. No errors that I can find in the operator logs.
NAME     SIZE   IMAGE            VERSION     STATUS    ENDPOINT   MESSAGE
hivemq   3      hivemq/hivemq4   k8s-4.8.4   Pending              Initial status

Any idea what this could be?

**Comment by leovanalphen** [comment]
Hi @ArtemZ 

The solution for us turned out to be to set admissionWebhooks to false, after a reinstall this fixed it for us:

> operator:
>   admissionWebhooks:
>     # Enable the admission hook
>     **enabled: false**

Another thing to check is that you have enough cpu and ram resources for the cluster you want to deploy. Otherwise the operator wont start cluster deployment.

Hope this helps!

**Comment by hurtadosanti** [comment]
Hi @leovanalphen we are glad you find a solution, usually looking at the events can help find issues `kubectl get events -A -w`
