### ISSUE TITLE
Helm Chart is outdated to k8s v1.25.x

### ISSUE THREAD

**Issue by stefanjay** [hivemq/helm-charts#90]
When do we can expect a patched helm chart to support k8s v1.25.x?
due to the changelog, `PodSecurityPolicy` is deprecated beginning in 1.25.x

https://kubernetes.io/docs/reference/using-api/deprecation-guide/#psp-v125

and the current helm chart [hivemq-operator-0.11.11](https://github.com/hivemq/helm-charts/releases/tag/hivemq-operator-0.11.11) is outdated:

```
❯ helm upgrade --install hivemq hivemq/hivemq-operator --namespace helm-test
Release "hivemq" does not exist. Installing it now.
Error: unable to build kubernetes objects from release manifest: resource mapping not found for name: "hivemq-hivemq-operator" namespace: "helm-test" from "": no matches for kind "PodSecurityPolicy" in version "policy/v1beta1"
ensure CRDs are installed first
```

**Comment by stefanjay** [comment]
I digged into the hivemq docu and found the workaround to disable the psp => https://www.hivemq.com/docs/operator/4.11/kubernetes-operator/configuration.html

**Comment by hurtadosanti** [comment]
Thanks @stefanjay yes given that https://kubernetes.io/docs/concepts/security/pod-security-policy/ are now deprectated
